version: "3.5"

services:
  bot:
    build:
      context: ./
    env_file:
      - ./config/.env
    restart: always
    depends_on:
      - db
    volumes:
      - ./:/var/bot/
  db:
    image: influxdb
    environment:
      INFLUXDB_ADMIN_ENABLED: "true"
    restart: always
    volumes:
      - data:/var/lib/influxdb
  http:
    image: abiosoft/caddy
    ports:
      - 80:80
      - 443:443
    env_file:
      - ./config/.env
    restart: always
    volumes:
      - ./config/Caddyfile:/etc/Caddyfile
      - ./config/.caddy:/root/.caddy
  grafana:
    image: grafana/grafana
    restart: always
    env_file:
      - ./config/.env
volumes:
  data: